spring:
  datasource:
    url: jdbc:mysql://123.207.36.107:3306/activiti?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # 数据库连接用户名称
    username: root
    # 数据库连接用户密码
    password: china321
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false
  freemarker:
    request-context-attribute: request
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
logging:
  level:
    root: info
server:
  port: 8090
  #context-path: /springboot-demo