spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kad?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    # 数据库连接用户名称
    username: root
    # 数据库连接用户密码
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false



  freemarker:
    request-context-attribute: request
    template-loader-path: classpath:/templates
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    root: info
    org.activiti.engine.impl.persistence.entity: debug


server:
  port: 8090
  #context-path: /springboot-demo
